import base64
import re
import subprocess
import tempfile
from pathlib import Path

import markdown as md_lib


CSS_STYLES = """
@page {
    margin: 2.5cm;
    @bottom-center {
        content: counter(page);
        font-size: 10pt;
        color: #666;
    }
}
body {
    font-family: Georgia, serif;
    font-size: 12pt;
    line-height: 1.8;
    color: #1a1a1a;
    max-width: 100%;
}
h1 { font-size: 28pt; margin-top: 2em; page-break-before: always; }
h2 { font-size: 20pt; margin-top: 1.5em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }
h3 { font-size: 14pt; margin-top: 1.2em; }
p { margin: 0.8em 0; text-align: justify; }
pre, code {
    font-family: "Courier New", monospace;
    font-size: 10pt;
    background: #f5f5f5;
    padding: 0.2em 0.4em;
    border-radius: 3px;
}
pre {
    padding: 1em;
    overflow-x: auto;
    border-left: 3px solid #ccc;
}
hr { border: none; border-top: 1px solid #ddd; margin: 2em 0; }
a { color: #1a1a1a; }
strong { font-weight: bold; }

/* ── Tables ──────────────────────────────────────────────────── */
table {
    border-collapse: collapse;
    width: 100%;
    margin: 1.5em 0;
    font-size: 11pt;
    page-break-inside: avoid;
}
thead th {
    background: #2c3e50;
    color: #ffffff;
    padding: 0.6em 1em;
    text-align: left;
    font-weight: bold;
}
tbody td {
    padding: 0.5em 1em;
    border-bottom: 1px solid #ddd;
    vertical-align: top;
}
tbody tr:nth-child(even) { background: #f4f6f8; }
tbody tr:hover { background: #eef1f4; }

/* ── Mermaid diagrams ────────────────────────────────────────── */
.mermaid-diagram {
    text-align: center;
    margin: 2em auto;
    page-break-inside: avoid;
}
.mermaid-diagram svg {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 0 auto;
}
.mermaid-fallback {
    background: #f8f8f8;
    border: 1px dashed #aaa;
    border-radius: 4px;
    padding: 1em;
    font-family: "Courier New", monospace;
    font-size: 9pt;
    text-align: left;
    white-space: pre;
}
"""

TITLE_PAGE_HTML = """
<div style="text-align:center; margin-top: 30%; page-break-after: always;">
  <h1 style="font-size: 36pt; border: none; page-break-before: avoid;">{title}</h1>
  <p style="font-size: 14pt; color: #666; margin-top: 2em;">Generated by Bookify</p>
</div>
"""

_MERMAID_PATTERN = re.compile(r"```mermaid\s*\n(.*?)\n```", re.DOTALL)

# Characters inside node labels that need quoting in Mermaid
_NEEDS_QUOTING = re.compile(r"\(|\)|->|<-|::")


def _sanitize_mermaid(code: str) -> str:
    """Auto-quote node labels that contain parentheses or arrow-like chars,
    which Mermaid's parser treats as shape/edge syntax otherwise."""
    def quote_label(m: re.Match) -> str:
        inner = m.group(1)
        # Already quoted — leave as-is
        if inner.startswith('"') and inner.endswith('"'):
            return m.group(0)
        if _NEEDS_QUOTING.search(inner):
            # Strip any stray inner quotes to avoid double-quoting
            inner = inner.replace('"', "'")
            return f'["{inner}"]'
        return m.group(0)

    return re.sub(r"\[([^\[\]]+)\]", quote_label, code)


def _render_mermaid_blocks(markdown_text: str) -> str:
    """Replace ```mermaid blocks with a PNG <img> (or fallback pre block).
    PNG avoids all SVG viewBox/scaling issues with WeasyPrint."""
    def replace(match: re.Match) -> str:
        code = _sanitize_mermaid(match.group(1).strip())
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                inp = Path(tmpdir) / "diagram.mmd"
                out = Path(tmpdir) / "diagram.png"
                inp.write_text(code, encoding="utf-8")
                result = subprocess.run(
                    ["mmdc", "-i", str(inp), "-o", str(out),
                     "-b", "white", "--quiet", "-w", "900"],
                    capture_output=True, text=True, timeout=30,
                )
                if result.returncode == 0 and out.exists():
                    b64 = base64.b64encode(out.read_bytes()).decode()
                    return (
                        f'\n<div class="mermaid-diagram">'
                        f'<img src="data:image/png;base64,{b64}" '
                        f'style="max-width:100%;height:auto;display:block;margin:0 auto;">'
                        f'</div>\n'
                    )
        except Exception:
            pass
        # Fallback: styled code block
        escaped = code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f'\n<div class="mermaid-diagram"><pre class="mermaid-fallback">{escaped}</pre></div>\n'

    return _MERMAID_PATTERN.sub(replace, markdown_text)


def markdown_to_html(book_markdown: str, title: str = "Building LLMs from Scratch") -> str:
    # Convert Mermaid blocks to inline SVG before markdown processing
    processed = _render_mermaid_blocks(book_markdown)

    extensions = ["fenced_code", "tables", "toc"]
    converter = md_lib.Markdown(extensions=extensions)
    body_html = converter.convert(processed)

    toc_html = ""
    if hasattr(converter, "toc"):
        toc_html = f'<div><h2>Table of Contents</h2>{converter.toc}</div>'

    title_html = TITLE_PAGE_HTML.format(title=title)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
</head>
<body>
  {title_html}
  {toc_html}
  {body_html}
</body>
</html>"""


def render_pdf(
    html_content: str,
    output_path: str = "output/book.pdf",
    progress=None,
) -> None:
    from weasyprint import HTML, CSS

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    if progress:
        progress.add_stage("Stage 6: Render PDF", total=1)

    HTML(string=html_content).write_pdf(
        output_path,
        stylesheets=[CSS(string=CSS_STYLES)],
    )

    if progress:
        progress.advance("Stage 6: Render PDF")
