import base64
import re
import subprocess
import tempfile
from pathlib import Path

import markdown as md_lib


CSS_STYLES = """
@page {
    margin: 2.5cm;
    @bottom-center {
        content: counter(page);
        font-size: 10pt;
        color: #666;
    }
}
@page :first {
    @bottom-center { content: none; }
}
body {
    font-family: Georgia, serif;
    font-size: 12pt;
    line-height: 1.4;
    color: #1a1a1a;
    max-width: 100%;
}
h1 { font-size: 26pt; margin-top: 0; margin-bottom: 0.4em; page-break-before: auto; }
h2 { font-size: 16pt; margin-top: 1.4em; margin-bottom: 0.3em; border-bottom: 1px solid #ccc; padding-bottom: 0.2em; }
h3 { font-size: 13pt; margin-top: 1em; margin-bottom: 0.2em; }
p { margin: 0.4em 0 0.6em; text-align: justify; }

/* ── Table of Contents ───────────────────────────────────────── */
.toc { margin: 0.5em 0 1.5em; }
.toc ul { list-style: none; padding-left: 1.2em; margin: 0.1em 0; }
.toc > ul { padding-left: 0; }
.toc li { margin: 0.25em 0; line-height: 1.4; }
.toc a { text-decoration: none; color: #1a1a1a; }
.toc li li { padding-left: 0.5em; border-left: 2px solid #e0e0e0; }
.toc li li a { color: #555; font-size: 11pt; }
pre, code {
    font-family: "Courier New", monospace;
    font-size: 10pt;
    background: #f5f5f5;
    padding: 0.2em 0.4em;
    border-radius: 3px;
}
pre {
    padding: 1em;
    overflow-x: auto;
    border-left: 3px solid #ccc;
}
hr { border: none; border-top: 1px solid #ddd; margin: 1.5em 0; }
a { color: #1a1a1a; }
strong { font-weight: bold; }
ul, ol { margin: 0.4em 0 0.8em; padding-left: 1.8em; }
li { margin: 0.2em 0; }
ol li { page-break-inside: avoid; }

/* ── Citations ───────────────────────────────────────────────── */
sup.cite-ref { font-size: 8pt; line-height: 0; vertical-align: super; }
sup.cite-ref a { color: #2563eb; text-decoration: underline; }
.references a { color: #2563eb; text-decoration: underline; }
.references {
    margin-top: 2em;
    padding-top: 1em;
    border-top: 1px solid #ddd;
    font-size: 10pt;
    color: #444;
    page-break-inside: avoid;
}
.references h4 { font-size: 11pt; margin-bottom: 0.5em; color: #1a1a1a; }
.references ol { padding-left: 1.5em; margin: 0; }
.references li { margin: 0.3em 0; line-height: 1.4; }

/* ── Counters ────────────────────────────────────────────────── */
body { counter-reset: figure-counter table-counter; }

/* ── Tables ──────────────────────────────────────────────────── */
table {
    border-collapse: collapse;
    width: 100%;
    margin: 0.5em 0 1.5em;
    font-size: 11pt;
    page-break-inside: avoid;
    counter-increment: table-counter;
}
caption {
    caption-side: top;
    text-align: center;
    font-style: italic;
    font-size: 10pt;
    color: #444;
    padding: 0 0 0.5em;
}
caption::before {
    content: "Table " counter(table-counter) ": ";
    font-weight: bold;
    font-style: normal;
}
thead th {
    background: #2c3e50;
    color: #ffffff;
    padding: 0.6em 1em;
    text-align: left;
    font-weight: bold;
}
tbody td {
    padding: 0.5em 1em;
    border-bottom: 1px solid #ddd;
    vertical-align: top;
}
tbody tr:nth-child(even) { background: #f4f6f8; }

/* ── Figures (Mermaid diagrams) ──────────────────────────────── */
figure.diagram {
    text-align: center;
    margin: 0.5em auto 0.8em;
    page-break-inside: auto;
    page-break-before: auto;
    counter-increment: figure-counter;
}
figure.diagram img {
    max-width: 85%;
    max-height: 340px;
    height: auto;
    width: auto;
    display: block;
    margin: 0 auto;
}
figure.diagram figcaption {
    font-style: italic;
    font-size: 10pt;
    color: #444;
    margin-top: 0.5em;
    text-align: center;
}
figure.diagram figcaption::before {
    content: "Figure " counter(figure-counter) ": ";
    font-weight: bold;
    font-style: normal;
}
.mermaid-fallback {
    background: #f8f8f8;
    border: 1px dashed #aaa;
    border-radius: 4px;
    padding: 1em;
    font-family: "Courier New", monospace;
    font-size: 9pt;
    text-align: left;
    white-space: pre;
}
"""

TITLE_PAGE_HTML = """
<div style="text-align:center; margin-top: 30%; page-break-after: always;">
  <h1 style="font-size: 36pt; border: none; page-break-before: avoid;">{title}</h1>
  <p style="font-size: 14pt; color: #666; margin-top: 2em;">Generated by Bookify</p>
</div>
"""

_MERMAID_PATTERN = re.compile(
    r"(?:\[FIGURE:\s*([^\]\n]+)\]\s*\n)?```mermaid\s*\n(.*?)\n```",
    re.DOTALL,
)
_TABLE_CAPTION_RE = re.compile(r"\[TABLE:\s*([^\]\n]+)\]\s*\n(\|)", re.MULTILINE)

# Citation regexes — applied to already-converted HTML so markdown never mangles
# the injected <sup>/<a> tags.
_VIDEO_CITE_RE = re.compile(
    r'\[Video:\s*["“](.+?)["”]\s*@\s*([0-9:\s,]+)\]',
    re.DOTALL,
)
# Matches [<a href="url">...</a>] — produced when markdown autolinks [<https://url>]
_URL_CITE_HTML_RE = re.compile(r'\[<a\s[^>]*href="(https?://[^"]+)"[^>]*>[^<]*</a>\]')
# Matches plain [https://url] as a fallback (no angle brackets)
_URL_CITE_PLAIN_RE = re.compile(r'\[(https?://[^\]\s<"]+)\](?!\()')


def _process_citations_in_html(html: str, id_prefix: str = "c") -> tuple:
    """Replace citation markers with superscript footnote numbers.
    Returns (processed_html, footnotes_html) — footnotes are NOT appended
    inline so the caller can place them at the end of the full document."""
    citations: dict = {}
    counter = [0]

    def _cite(key: str, display: str) -> str:
        if key not in citations:
            counter[0] += 1
            citations[key] = (counter[0], display)
        n = citations[key][0]
        return f'<sup class="cite-ref"><a href="#{id_prefix}-{n}">[{n}]</a></sup>'

    def replace_video(m: re.Match) -> str:
        return _cite(m.group(0), f'Video: <em>{m.group(1)}</em> @ {m.group(2)}')

    def replace_url(m: re.Match) -> str:
        url = m.group(1)
        return _cite(m.group(0), f'<a href="{url}">{url}</a>')

    out = _VIDEO_CITE_RE.sub(replace_video, html)
    out = _URL_CITE_HTML_RE.sub(replace_url, out)
    out = _URL_CITE_PLAIN_RE.sub(replace_url, out)

    footnotes_html = ""
    if citations:
        items = "".join(
            f'<li id="{id_prefix}-{n}">{text}</li>\n'
            for _, (n, text) in citations.items()
        )
        footnotes_html = (
            f'<div class="references"><h4>Footnotes</h4>'
            f'<ol>\n{items}</ol></div>\n'
        )
    return out, footnotes_html


def _process_citations_all_html(html: str) -> str:
    """Apply one global citation index and append a single footnotes block."""
    body, footnotes = _process_citations_in_html(html, id_prefix="fn")
    return body + ("\n" + footnotes if footnotes else "")

# Characters inside node labels that need quoting in Mermaid
_NEEDS_QUOTING = re.compile(r"\(|\)|->|<-|::")


def _sanitize_mermaid(code: str) -> str:
    """Auto-quote node labels that contain parentheses or arrow-like chars,
    which Mermaid's parser treats as shape/edge syntax otherwise."""
    def quote_label(m: re.Match) -> str:
        inner = m.group(1)
        # Already quoted — leave as-is
        if inner.startswith('"') and inner.endswith('"'):
            return m.group(0)
        if _NEEDS_QUOTING.search(inner):
            # Strip any stray inner quotes to avoid double-quoting
            inner = inner.replace('"', "'")
            return f'["{inner}"]'
        return m.group(0)

    return re.sub(r"\[([^\[\]]+)\]", quote_label, code)


def _normalize_markdown_blocks(markdown_text: str) -> str:
    """Normalize common malformed LLM markdown so renderer can parse reliably."""
    text = markdown_text.replace("\r\n", "\n")

    # Promote flowchart/graph fenced blocks to proper mermaid fences.
    text = re.sub(
        r'(\[FIGURE:\s*[^\]\n]+\]\s*\n)```(flowchart|graph)\s+([^\n]+)',
        lambda m: f"{m.group(1)}```mermaid\n{m.group(2)} {m.group(3)}",
        text,
    )

    # Drop orphan figure caption markers that are not followed by a mermaid block.
    text = re.sub(
        r'^\[FIGURE:\s*[^\]\n]+\]\s*\n(?!```mermaid)',
        '',
        text,
        flags=re.MULTILINE,
    )

    # Ensure fenced blocks start on their own line so markdown parses them.
    text = re.sub(r'([^\n])(```(?:[a-zA-Z0-9_-]+)?)', r"\1\n\2", text)

    # Ensure headings start on their own line (fixes leaked ### headings).
    text = re.sub(r'([^\n])(#{2,3}\s)', r"\1\n\2", text)

    # Avoid runaway vertical whitespace after normalization.
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text


def _render_mermaid_blocks(markdown_text: str) -> str:
    """Replace ```mermaid blocks (with optional [FIGURE: title]) with a
    numbered <figure> containing a PNG image. PNG avoids WeasyPrint SVG issues."""
    def replace(match: re.Match) -> str:
        caption = (match.group(1) or "").strip()
        code = _sanitize_mermaid(match.group(2).strip())
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                inp = Path(tmpdir) / "diagram.mmd"
                out = Path(tmpdir) / "diagram.png"
                inp.write_text(code, encoding="utf-8")
                result = subprocess.run(
                    ["mmdc", "-i", str(inp), "-o", str(out),
                     "-b", "white", "--quiet", "-w", "650"],
                    capture_output=True, text=True, timeout=30,
                )
                if result.returncode == 0 and out.exists():
                    b64 = base64.b64encode(out.read_bytes()).decode()
                    return (
                        f'\n<figure class="diagram">'
                        f'<img src="data:image/png;base64,{b64}">'
                        f'<figcaption>{caption}</figcaption>'
                        f'</figure>\n'
                    )
        except Exception:
            pass
        escaped = code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return (
            f'\n<figure class="diagram">'
            f'<pre class="mermaid-fallback">{escaped}</pre>'
            f'<figcaption>{caption}</figcaption>'
            f'</figure>\n'
        )

    return _MERMAID_PATTERN.sub(replace, markdown_text)


def _inject_table_captions(markdown_text: str) -> str:
    """Convert [TABLE: title] markers to HTML comments that survive markdown
    conversion, then inject <caption> into each rendered <table>."""
    # Mark table captions as HTML comments before markdown processing
    return _TABLE_CAPTION_RE.sub(
        lambda m: f'<!--TABLECAP:{m.group(1).strip()}-->\n{m.group(2)}',
        markdown_text,
    )


def _inject_captions_into_html(html: str) -> str:
    """Post-process HTML: inject <caption> into every <table>.
    Tables preceded by <!--TABLECAP:title--> get that title; others get empty caption for CSS counter."""
    # With a preceding caption comment
    html = re.sub(
        r'<!--TABLECAP:([^>]*)-->\s*(<table[^>]*>)',
        lambda m: f'{m.group(2)}<caption>{m.group(1)}</caption>',
        html,
    )
    # Tables without any caption marker — add empty caption for CSS counter
    html = re.sub(
        r'(<table[^>]*>)(?!\s*<caption)',
        r'\1<caption></caption>',
        html,
    )
    return html


def markdown_to_html(book_markdown: str, title: str = "Building LLMs from Scratch") -> str:
    book_markdown = _normalize_markdown_blocks(book_markdown)
    # 1. Extract [TABLE: title] markers before markdown eats them
    processed = _inject_table_captions(book_markdown)
    # 2. Render mermaid blocks (with optional [FIGURE: title]) to PNG figures
    processed = _render_mermaid_blocks(processed)

    extensions = ["fenced_code", "tables", "toc"]
    converter = md_lib.Markdown(extensions=extensions)
    body_html = converter.convert(processed)

    # 3. Inject <caption> into every <table>
    body_html = _inject_captions_into_html(body_html)
    # 4. Replace citation markers with superscript footnotes — must run on final
    #    HTML so the markdown converter never touches the injected <sup>/<a> tags
    body_html = _process_citations_all_html(body_html)

    toc_html = ""
    if hasattr(converter, "toc"):
        toc_html = f'<div><h2>Table of Contents</h2>{converter.toc}</div>'

    title_html = TITLE_PAGE_HTML.format(title=title)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
</head>
<body>
  {title_html}
  {toc_html}
  {body_html}
</body>
</html>"""


def render_pdf(
    html_content: str,
    output_path: str = "output/book.pdf",
    progress=None,
) -> None:
    from weasyprint import HTML, CSS

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    if progress:
        progress.add_stage("Stage 6: Render PDF", total=1)

    HTML(string=html_content).write_pdf(
        output_path,
        stylesheets=[CSS(string=CSS_STYLES)],
    )

    if progress:
        progress.advance("Stage 6: Render PDF")
