from pathlib import Path

import markdown as md_lib


CSS_STYLES = """
@page {
    margin: 2.5cm;
    @bottom-center {
        content: counter(page);
        font-size: 10pt;
        color: #666;
    }
}
body {
    font-family: Georgia, serif;
    font-size: 12pt;
    line-height: 1.8;
    color: #1a1a1a;
    max-width: 100%;
}
h1 { font-size: 28pt; margin-top: 2em; page-break-before: always; }
h2 { font-size: 20pt; margin-top: 1.5em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }
h3 { font-size: 14pt; margin-top: 1.2em; }
p { margin: 0.8em 0; text-align: justify; }
pre, code {
    font-family: "Courier New", monospace;
    font-size: 10pt;
    background: #f5f5f5;
    padding: 0.2em 0.4em;
    border-radius: 3px;
}
pre {
    padding: 1em;
    overflow-x: auto;
    border-left: 3px solid #ccc;
}
hr { border: none; border-top: 1px solid #ddd; margin: 2em 0; }
a { color: #1a1a1a; }
strong { font-weight: bold; }
"""

TITLE_PAGE_HTML = """
<div style="text-align:center; margin-top: 30%; page-break-after: always;">
  <h1 style="font-size: 36pt; border: none; page-break-before: avoid;">{title}</h1>
  <p style="font-size: 14pt; color: #666; margin-top: 2em;">Generated by Bookify</p>
</div>
"""


def markdown_to_html(book_markdown: str, title: str = "Building LLMs from Scratch") -> str:
    extensions = ["fenced_code", "tables", "toc"]
    converter = md_lib.Markdown(extensions=extensions)
    body_html = converter.convert(book_markdown)

    toc_html = ""
    if hasattr(converter, "toc"):
        toc_html = f'<div><h2>Table of Contents</h2>{converter.toc}</div>'

    title_html = TITLE_PAGE_HTML.format(title=title)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
</head>
<body>
  {title_html}
  {toc_html}
  {body_html}
</body>
</html>"""


def render_pdf(
    html_content: str,
    output_path: str = "output/book.pdf",
    progress=None,
) -> None:
    from weasyprint import HTML, CSS

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    if progress:
        progress.add_stage("Stage 6: Render PDF", total=1)

    HTML(string=html_content).write_pdf(
        output_path,
        stylesheets=[CSS(string=CSS_STYLES)],
    )

    if progress:
        progress.advance("Stage 6: Render PDF")
